import React from "react"

import { Inter } from "next/font/google"

import StyledComponentsRegistry from "@/lib/AntdRegistry"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({ children }: React.PropsWithChildren): React.ReactNode => (
  <html lang='en'>
    <body className={inter.className} suppressHydrationWarning={true}>
      <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
    </body>
  </html>
)

export default RootLayout
