export { default as DashboardLayout } from "./Layout/layout"
export { default as AccountLoginForm } from "./accountLoginForm/accountLoginForm"
export { default as PhoneLoginForm } from "./phoneLoginForm/phoneLoginForm"
export { default as UserBasicInfo } from "./userBasicInfo/userBasicInfo"
export { default as UserSecuritySetting } from "./userSecuritySetting/userSecuritySetting"
