import React from "react"

import DashBoardLayout from "@/components/Layout/layout"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({ children }: React.PropsWithChildren): React.ReactNode => (
  <div>
    <DashBoardLayout>{children}</DashBoardLayout>
  </div>
)

export default RootLayout
